version: "2"

services:
  master:
    image: erkules/galera:basic
    container_name: master
    volumes:
      - /data:/var/lib/mysql
    networks:
      - mysql
    command: --wsrep-cluster-name=local-test --wsrep-cluster-address=gcomm://

  slave:
    depends_on:
      - master
    image: erkules/galera:basic
    networks:
      - mysql
    command: --wsrep-cluster-name=local-test --wsrep-cluster-address=gcomm://master

networks:
  mysql:
